apiVersion: v1
kind: Service
metadata:
  name: {{ include "bob.fullname" . }}
  labels:
    {{- include "bob.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bob.service.type }}
  ports:
    - name: chat
      port: {{ .Values.bob.service.chatPort }}
      targetPort: chat
      protocol: TCP
    - name: mcp
      port: {{ .Values.bob.service.mcpPort }}
      targetPort: mcp
      protocol: TCP
  selector:
    {{- include "bob.selectorLabels" . | nindent 4 }}
